#!/usr/bin/env python3

import glob
import logging
import os
import subprocess
import sys
import tempfile
import tarfile

import mytool

if __name__ == '__main__':
    logging.getLogger().setLevel(logging.INFO)

    site_pkg = mytool.__path__[0]

    try:
        from subtool import cli
    except ImportError:
        # Install the subpackage.
        subprocess.check_call(f'{sys.executable} -m pip install {site_pkg}'.split())

        from subtool import cli

    with tempfile.TemporaryDirectory() as tmpdir:
        # Convert subpackage to a tarball
        os.chdir(site_pkg)
        subprocess.check_call(
            f'{sys.executable} ./setup.py sdist --dist-dir {tmpdir}'.split(),
        )

        # Set tarball as extra packages for Beam.
        pkg_archive = glob.glob(os.path.join(tmpdir, '*.tar.gz'))[0]

        with tarfile.open(pkg_archive, 'r') as tar:
            py_files_in_tar = [f for f in tar.getnames() if f.endswith('.py')]
            assert len(py_files_in_tar) > 0, 'extra_package must include python files!'

        cli(['--extra_package', pkg_archive])
