#!/usr/bin/env python3

import tempfile
import glob
import os
import sys
from mytool.subtool import cli
from apache_beam.utils import processes

import logging


if __name__ == '__main__':

    logging.getLogger().setLevel(logging.INFO)

    with tempfile.TemporaryDirectory() as tmpdir:
        processes.check_output(
            f'{sys.executable} ./setup.py sdist --dist-dir {tmpdir}'.split(),
            stderr=processes.STDOUT
        )

        dist_files = glob.glob(os.path.join(tmpdir, '*.tar.gz'))

        cli(['--extra_package', dist_files[0]])

