#!/usr/bin/env python3

import glob
import logging
import os
import subprocess
import sys
import tempfile

import mytool

if __name__ == '__main__':
    logging.getLogger().setLevel(logging.INFO)

    with tempfile.TemporaryDirectory() as tmpdir:
        site_pkg = mytool.__path__[0]

        # Install the subpackage.
        subprocess.check_call(f'{sys.executable} -m pip install {site_pkg}'.split())

        from subtool import cli

        # Convert subpackage to a tarball
        subprocess.check_call(
            f'{sys.executable} {site_pkg}/setup.py sdist --dist-dir {tmpdir}'.split(),
        )

        # Set tarball as extra packages for Beam.
        dist_files = glob.glob(os.path.join(tmpdir, '*.tar.gz'))
        cli(['--extra_package', dist_files[0]])
